export const SRI_LANKA_COUNTRY = "Sri Lanka";

export const SRI_LANKA_PROVINCES = [
  "Western",
  "Central",
  "Southern",
  "Northern",
  "Eastern",
  "North Western",
  "North Central",
  "Uva",
  "Sabaragamuwa",
];

// A consolidated list of major towns/cities in Sri Lanka.
// You can extend this further if you need absolutely all GN-level locations.
export const SRI_LANKA_TOWNS = [
  "Colombo",
  "Dehiwala-Mount Lavinia",
  "Moratuwa",
  "Sri Jayawardenepura Kotte",
  "Negombo",
  "Kandy",
  "Gampola",
  "Matale",
  "Nuwara Eliya",
  "Galle",
  "Matara",
  "Hambantota",
  "Jaffna",
  "Kilinochchi",
  "Mannar",
  "Vavuniya",
  "Mullaitivu",
  "Batticaloa",
  "Trincomalee",
  "Ampara",
  "Kalmunai",
  "Kurunegala",
  "Kuliyapitiya",
  "Puttalam",
  "Chilaw",
  "Anuradhapura",
  "Polonnaruwa",
  "Badulla",
  "Bandarawela",
  "Monaragala",
  "Ratnapura",
  "Kegalle",
  "Avissawella",
  "Gampaha",
  "Ja-Ela",
  "Kelaniya",
  "Kadawatha",
  "Ragama",
  "Wattala",
  "Panadura",
  "Horana",
  "Beruwala",
  "Kalutara",
  "Aluthgama",
  "Bentota",
  "Ambalangoda",
  "Hikkaduwa",
  "Tangalle",
  "Embilipitiya",
  "Hatton",
  "Talawakele",
  "Ratnapura",
  "Kegalle",
  "Maharagama",
  "Kottawa",
  "Homagama",
  "Piliyandala",
  "Boralesgamuwa",
  "Mawanella",
  "Weligama",
  "Akuressa",
  "Danniyaya",
];

